### ISSUE TITLE
delay_off functionality?

### ISSUE THREAD

**Issue by djshubs** [kevinvincent/ha-wyzesense#137]
The standard time for motion reporting for Wyze Motion is 40 seconds. Does anyone have suggestions on how to set up a delay_off so that it continues to report "on" for a period of time as defined by the user? 

For reference: https://www.home-assistant.io/integrations/binary_sensor.template/

**Comment by eschrip** [comment]
I have used node-red to implement a longer delay.  Basically starting my own timer.

**Comment by VarenDerpsAround** [comment]
template binary sensor

on / off > could template it however

of automation, upon trigger of sensor, switch template sensor on, but not off once the motion sensor goes off, but off 40 seconds later, via a different automation. I'll throw up an example for giggles.

**Comment by VarenDerpsAround** [comment]
```
- id: '1593752154463'
  alias: Wyze Sensor Timed off (on)
  description: Turn on the Timed Wyze Sensor
  trigger:
  - entity_id: binary_sensor.door_front
    for: '0'
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.template_binary_sensor
    service: input_boolean.turn_on
- id: '1593752230422'
  alias: Wyze Sensor Timed off (off)
  description: Turn off the Timed Wyze Sensor
  trigger:
  - entity_id: binary_sensor.door_front
    for: '40'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.template_binary_sensor
    service: input_boolean.turn_off
```

Does this satisfy the needs? I just created the input_boolean.template_binary_sensor in the helpers menu for hassos.
