### ISSUE TITLE
Persistent Devices

### ISSUE THREAD

**Issue by Techtony96** [kevinvincent/ha-wyzesense#185]
Hi, I am trying to setup my Home Assistant so I can easily create/destroy the instance (for backup purposes) only having to copy over the config files. Is it possible to specify the MAC addresses of the sensors I have in the config file so I do not have to repair them when setting up a new home assistant install?

Something like:

```yml
binary_sensor:
  - platform: wyzesense
    device: /dev/wyzesense
    mac:
      - asdf1234
      - foo1234
```
