### ISSUE TITLE
Config Check fails after Switching RPi 4 to SSD

### ISSUE THREAD

**Issue by 51av0sh** [kevinvincent/ha-wyzesense#214]
A few days ago I migrated my pi setup from SD to SSD. Performed a full restore from my latest snapshot and had a few issues that needed to be fixed relating to the DB but everything else worked fine except the wyzesense integration. I can't get past the config check with the following error:

Platform error binary_sensor.wyzesense - cannot import name 'retry' from 'retry' (/usr/local/lib/python3.8/site-packages/retry/__init__.py)

I setup debug logging for the component but there is absolutely nothing in the logs about wyzesense or any errors

```
logger:
  default: info
  logs:
    custom_components.wyzesense: debug
    wyzesense.gateway: debug
```

I've tried removing the integration, removing HACS, and reinstalling but no dice (several times). I'm lost at this point. Any suggestions?
