### ISSUE TITLE
battery sensor

### ISSUE THREAD

**Issue by basesnow** [kevinvincent/ha-wyzesense#90]
Wondering if each sensor can also report battery level as a sensor too? Would like a simple way to display all my battery levels so I can see what needs to be changed before it dies. Hopefully, integrating something like that wouldn't tax the battery more than the current setup.

**Comment by JoshuaMulliken** [comment]
@basesnow You can create your own with:
```yaml
sensor:
  - platform: template
    sensors:
      wyzesense_<MAC>_battery_level:
        friendly_name: "<DEVICE NAME> Battery Level"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('binary_sensor.wyzesense_<MAC>', 'battery_level') }}"
        device_class: battery
```
