### ISSUE TITLE
Set up failure - Will not recognize Wyze hub

### ISSUE THREAD

**Issue by ha14937** [kevinvincent/ha-wyzesense#91]
Running HASSIO on Oracle VM; installed WyzeSense via HACS with no apparent issues. Files show up in the `/config/custom_components` folder

I had it set up a few weeks ago with no issues. VM crashed (unrelated issue) and I had to rebuild - and can't get WyzeSense to work now. 

- Error logs here: https://pastebin.com/gfNhGqXv
- You will see three sets of logs; I changed the config three times for testing/logging purposes
- Error log contains all three attempts, separate by comment blocks.

**Comment by kevinvincent** [comment]
Try changing "Auto" to "auto".

**Comment by TimothyLeeAdams** [comment]
I'm having this exact same issue. Identical error logs and everything. I've been running this component for the past couple of months and it had been flawless up until yesterday. I'm running Home Assistant in Docker on an unRaid host. Have also tried all three of the following configs:
```
binary_sensor:
  - platform: wyzesense
    device: auto

binary_sensor:
  - platform: wyzesense
    device: "/dev/hidraw0"

binary_sensor:
  - platform: wyzesense
    device: "/dev/hidraw1"

```
Just to try and isolate the issue, I set up a fresh instance of Home Assistant with only HACS and WyzeSense component installed and am still having the same issue.

I updated to WYZESENSE v0.0.7 and Home Assistant 0.104.2 at the same time, so not sure it wasn't something that changed in Home Assistant that is causing the issue. I might try downgrading Home Assistant and/or WyzeSense versions to see if I can find a working combination and will report back here if I find anything.
